apiVersion: apps/v1
kind: Deployment
metadata:
  name: ysjdb
  labels:
    app: ysjdb
spec:
  selector:
    matchLabels:
      app: ysjdb
  replicas: 1
  template:
    metadata:
      labels:
        app: ysjdb
    spec:
      containers:
      - name: ysjdb 
        image: vprofile/vprofiledb
        args:
         - "--ignore-db-dir=lost+found"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass
      nodeSelector:
        zone: us-east-2b
      volumes:
        - name: vpro-db-data
          # This AWS EBS volume must already exist.
          awsElasticBlockStore:
             volumeID: EBSVolumeID
             fsType: ext4
